#!/bin/bash

# Script to fix COROTests dependencies
# This script provides instructions for fixing the test target

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_PATH="$SCRIPT_DIR/CORO.xcodeproj"

echo "================================================"
echo "Fixing COROTests Dependencies"
echo "================================================"
echo ""

echo "The error 'Missing required module _NumericsShims' means"
echo "the test target doesn't have access to Swift packages."
echo ""
echo "Here are 2 ways to fix this:"
echo ""
echo "================================================"
echo "Method 1: Using Xcode (RECOMMENDED)"
echo "================================================"
echo ""
echo "1. Open Xcode (if not already open)"
echo "2. Click on 'CORO' project (blue icon at top of navigator)"
echo "3. Select 'COROTests' target in the middle panel"
echo "4. Click 'Build Phases' tab"
echo "5. Expand 'Link Binary With Libraries'"
echo "6. Click '+' button"
echo "7. Add these packages:"
echo "   - MLX"
echo "   - MLXNN"
echo "   - MLXLLM"
echo "   - MLXLMCommon"
echo "   - Numerics (from swift-numerics)"
echo "8. Click 'Build Settings' tab"
echo "9. Search for 'Other Linker Flags'"
echo "10. Make sure it has the same flags as CORO target"
echo ""
echo "Then run tests with: Cmd + U"
echo ""
echo "================================================"
echo "Method 2: Clean and Reset (if Method 1 fails)"
echo "================================================"
echo ""
echo "1. In Xcode: Product → Clean Build Folder (Cmd+Shift+K)"
echo "2. Close Xcode"
echo "3. Run this in Terminal:"
echo ""
echo "   cd '$SCRIPT_DIR'"
echo "   rm -rf ~/Library/Developer/Xcode/DerivedData/*CORO*"
echo "   rm -rf .build"
echo "   rm -rf CORO.xcodeproj/project.xcworkspace/xcshareddata/swiftpm"
echo ""
echo "4. Re-open Xcode"
echo "5. File → Packages → Resolve Package Versions"
echo "6. Wait for packages to resolve"
echo "7. Follow Method 1 steps above"
echo ""
echo "================================================"
echo "Method 3: Simplify Tests (Quick Workaround)"
echo "================================================"
echo ""
echo "If you want to run tests without MLX dependencies:"
echo ""
echo "1. Comment out MLX-related tests in ChatViewModelTests.swift"
echo "2. Remove the MockMLXService class"
echo "3. Tests will run without on-device model testing"
echo ""
echo "This allows you to test most functionality while"
echo "we sort out the MLX package dependencies."
echo ""
echo "================================================"
echo ""

# Try to open Xcode
if [ -d "$PROJECT_PATH" ]; then
    echo "Opening Xcode..."
    open "$PROJECT_PATH"
    sleep 2
    echo "✅ Xcode opened!"
else
    echo "❌ Project not found at: $PROJECT_PATH"
fi

echo ""
echo "For more help, see:"
echo "COROTests/README.md"
echo ""
